<!doctype html><html><head><meta charset="utf-8"><title>Barangay Clearance</title><style>
@page{margin:17mm 20mm 16mm}*{box-sizing:border-box}body{margin:0;color:#263238;font:10.5pt/1.55 'DejaVu Sans',sans-serif}.reference{text-align:right;font-size:8.5pt;color:#52606d}.header{text-align:center;margin:2mm 0 9mm;padding-bottom:5mm;border-bottom:2pt double #1e3a5f}.logo{width:19mm;height:19mm;object-fit:contain;margin-bottom:2mm}.header h1{margin:0;color:#1e3a5f;font-size:16pt;text-transform:uppercase}.header h2{margin:1mm 0;color:#1e3a5f;font-size:13pt}.header p{margin:0;color:#64748b;font-size:8.5pt}.title{text-align:center;margin:8mm 0}.title h3{display:inline-block;margin:0;padding:2.5mm 12mm;border:1.2pt solid #1e3a5f;font-size:13pt;letter-spacing:1.5pt;text-transform:uppercase}.body-text{margin-top:8mm;text-align:justify;line-height:1.75}.body-text p{margin:0 0 5mm}.info-table{width:100%;margin:7mm 0 0;border-collapse:collapse;page-break-inside:avoid}.info-table td{padding:2mm 2.5mm;border-bottom:.4pt solid #d8dee4;vertical-align:top}.info-table .label{width:34%;font-weight:bold;color:#334e68}.signature{width:68mm;margin:18mm 0 0 auto;text-align:center;page-break-inside:avoid}.signature .caption{margin:0 0 11mm;text-align:left;font-size:8.5pt;color:#64748b}.signature .name{min-height:7mm;margin:0;border-bottom:.7pt solid #263238;font-weight:bold;text-transform:uppercase}.signature .position{margin:2mm 0 0;font-size:9pt;color:#52606d}.footer{position:fixed;right:0;bottom:-10mm;left:0;padding-top:2mm;border-top:.4pt solid #cbd5e1;text-align:center;font-size:7pt;line-height:1.35;color:#718096}
</style></head><body>
<div class="reference">Clearance No. {{ str_pad($resident->id,6,'0',STR_PAD_LEFT) }}</div>
<div class="header"><img src="{{ public_path('images/logo.png') }}" alt="" class="logo"><h1>Republic of the Philippines</h1><h2>Barangay {{ config('app.barangay_name',$resident->purok ?: 'N/A') }}</h2><p>{{ config('app.name') }}</p></div>
<div class="title"><h3>Barangay Clearance</h3></div>
<div class="body-text"><p><strong>TO WHOM IT MAY CONCERN:</strong></p><p>This is to certify that <strong>{{ $resident->full_name }}</strong>, of legal age, {{ strtolower($resident->civil_status) }}, Filipino, and a resident of Barangay {{ config('app.barangay_name',$resident->purok ?: 'N/A') }}, has been known to be a person of good moral character and has not been involved in activities that would impair the safety and welfare of the community.</p><p>This clearance is issued upon the request of the above-named person for <strong>general purposes</strong>.</p></div>
<table class="info-table"><tr><td class="label">Name</td><td>{{ $resident->full_name }}</td></tr><tr><td class="label">Birth Date</td><td>{{ $resident->birth_date->format('F d, Y') }}</td></tr><tr><td class="label">Place of Birth</td><td>{{ $resident->birthplace ?: 'N/A' }}</td></tr><tr><td class="label">Gender</td><td>{{ ucfirst($resident->gender) }}</td></tr><tr><td class="label">Civil Status</td><td>{{ ucfirst($resident->civil_status) }}</td></tr><tr><td class="label">Address</td><td>{{ $resident->street_address ?: ($resident->purok ?: 'N/A') }}</td></tr><tr><td class="label">Date Issued</td><td>{{ now()->format('F d, Y') }}</td></tr></table>
<div class="signature"><p class="caption">Certified by:</p><p class="name">{{ auth()->user()?->name ?: '' }}</p><p class="position">{{ auth()->user()?->role_label ?: 'Barangay Official' }}</p></div>
<div class="footer">System-generated clearance &mdash; Barangay Concepcion Information Management System</div>
</body></html>
