@extends('layouts.app')
@section('title',$template->exists?'Edit Template':'Create Template')
@section('header',$template->exists?'Edit Document Template':'Create Document Template')
@section('content')
<div class="space-y-5" x-data="{title:@js(old('title',$template->title)),body:@js(old('body',$template->body))}">
<div class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Temporary generic template. Replace or update this template when the approved official barangay document format becomes available. This notice is never printed.</div>
<form method="POST" enctype="multipart/form-data" action="{{ $template->exists?route('document-templates.update',$template):route('document-templates.store') }}" class="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">@csrf @if($template->exists)@method('PUT')@endif
<div class="space-y-5 rounded-xl border bg-white p-4 sm:p-6">
@foreach([['name','Template Name'],['title','Document Title'],['header_line_1','Header Line 1'],['header_line_2','Header Line 2'],['header_line_3','Header Line 3'],['office_name','Office Name'],['barangay_name','Barangay Name'],['municipality','Municipality/City'],['province','Province'],['signatory_name','Signatory Name'],['signatory_position','Signatory Position']] as [$field,$label])<label class="block"><span class="mb-1 block text-sm font-medium">{{ $label }}</span><input @if($field==='title') x-model="title" @endif name="{{ $field }}" value="{{ old($field,$template->{$field}) }}" {{ in_array($field,['name','title'])?'required':'' }} class="min-h-11 w-full rounded-lg border-gray-300"></label>@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror @endforeach
@foreach([['opening_phrase','Opening Phrase',3],['body','Certificate Body',10],['closing_text','Closing Statement',4],['footer_text','Footer Text',3]] as [$field,$label,$rows])<label class="block"><span class="mb-1 block text-sm font-medium">{{ $label }}</span><textarea @if($field==='body') x-model="body" @endif name="{{ $field }}" rows="{{ $rows }}" {{ $field==='body'?'required':'' }} class="w-full rounded-lg border-gray-300">{{ old($field,$template->{$field}) }}</textarea></label>@error($field)<p class="text-sm text-red-600">{{ $message }}</p>@enderror @endforeach
<fieldset><legend class="mb-2 text-sm font-medium">Display Options</legend><div class="grid gap-2 sm:grid-cols-2">@foreach(['show_control_number'=>'Control number','show_fee'=>'Fee','show_issue_date'=>'Issue date','show_resident_photo'=>'Resident photo','show_logo'=>'Logo / seal','is_active'=>'Active'] as $field=>$label)<label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field,$template->exists?$template->{$field}:in_array($field,['show_control_number','show_issue_date','is_active'])))><span>{{ $label }}</span></label>@endforeach</div></fieldset>
<label class="block"><span class="mb-1 block text-sm font-medium">Optional Logo/Seal (JPG, PNG, WebP; 2 MB)</span><input type="file" name="logo" accept="image/jpeg,image/png,image/webp" class="min-h-11 w-full"></label>@if($template->logo_path)<label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="remove_logo" value="1">Remove configured image</label>@endif
<fieldset><legend class="mb-2 text-sm font-medium">Assign Document Types</legend><div class="grid gap-2 sm:grid-cols-2">@foreach($documentTypes as $type)<label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="document_type_ids[]" value="{{ $type->id }}" @checked(in_array($type->id,old('document_type_ids',$template->documentTypes?->pluck('id')->all()??[])))><span>{{ $type->name }}</span></label>@endforeach</div></fieldset>
<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><a href="{{ route('document-templates.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-lg border px-4">Cancel</a><button class="min-h-11 rounded-lg bg-brand-800 px-5 text-white">Save Template</button></div>
</div>
<aside class="space-y-4"><div class="rounded-xl border bg-white p-4"><h3 class="font-semibold">Available Placeholders</h3><div class="mt-3 flex flex-wrap gap-2">@foreach($placeholders as $placeholder)<code class="rounded bg-gray-100 px-2 py-1 text-xs">@{{ '{{'.$placeholder.'}}' }}</code>@endforeach</div><p class="mt-3 text-xs text-gray-500">Unknown placeholders display as [UNKNOWN: name] and never execute.</p></div><div class="rounded-xl border bg-white p-5"><p class="text-center text-xs">Generic safe sample preview</p><h3 class="my-5 text-center text-lg font-bold" x-text="title||'Document title'"></h3><p class="whitespace-pre-line text-sm" x-text="body||'Certificate body'"></p></div></aside>
</form></div>
@endsection
